name: Docker Image CI

on:
  schedule:
    - cron: "10 6 1 * *"
  push:
    paths:
      - .trigger
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_base_images: ["alpine"]
        latest_tag: ["false"]
        include:
          - docker_base_images: "alpine:latest"
            latest_tag: "true"
    steps:
      - uses: actions/checkout@v1
      - run: bash ./scripts/build.sh
        env:
          DOCKER_BASE_IMAGE: ${{ matrix.docker_base_images }}
          LATEST_TAG: ${{ matrix.latest_tag }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PUSH: "true"
